language: ruby
sudo: false
cache:
  directories:
    - vendor/bundle
    - vendor/modules
rvm:
  - 1.9.3
env:
  - PUPPET_RSPEC_STRICT_VARIABLES=0
  - PUPPET_RSPEC_STRICT_VARIABLES=1
  - PUPPET_RSPEC_FUTURE_PARSER=0
  - PUPPET_RSPEC_FUTURE_PARSER=1
before_install:
  # Travis bundler versions are quite out of date and can cause install errors
  # see: https://github.com/rubygems/rubygems/issues/1419
  # TODO: recheck 2018/01/13
  # This has been commented out until the following issues are resolved
  # https://github.com/bundler/bundler/issues/6144
  # https://github.com/rubygems/rubygems/issues/2055
  #- gem update bundler
install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec rake librarian:install
script:
  - bundle exec rake lint
  - bundle exec rake all_but_lint
matrix:
  fast_finish: true
  allow_failures:
    - env: PUPPET_RSPEC_STRICT_VARIABLES=1
    - env: PUPPET_RSPEC_FUTURE_PARSER=1
